FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest

ENV PKG_CONFIG_ALLOW_CROSS 1
ENV PKG_CONFIG_PATH /usr/lib/aarch64-linux-gnu/pkgconfig/

RUN dpkg --add-architecture arm64 && \
  apt-get update && \
  apt-get install -y libasound2-dev:arm64 libdbus-1-dev:arm64 \